### ISSUE TITLE
Allow several served directories

### ISSUE THREAD

**Issue by deurk** [Myster-Tee/TinfoilWebServer#1]
Would be great to be able to set several directories (potentially hosted on several disks, etc) in a transparent way for the client.

**Comment by Myster-Tee** [comment]
Yes, that's a cool idea, I'll implement this ;)

**Comment by deurk** [comment]
Any idea when you'll have free time to? :)

**Comment by Myster-Tee** [comment]
Soon ;)

**Comment by deurk** [comment]
Great, looking forward to it :)

**Comment by Myster-Tee** [comment]
v1.1.0 released, let me know if it does the job :)

**Comment by deurk** [comment]
Hey, thanks a lot! Will give a whirl and let you know!

**Comment by deurk** [comment]
I don't seem to be able to get it to take into account `ServedDirectories`

**Comment by deurk** [comment]
Nervermind my previous comment, I found the issue. Copied the line I used before and noticed you changed `ServedDirectory` to `ServedDirectories`. It now works as intented. Thanks a lot :)

**Comment by Myster-Tee** [comment]
Perfect, I close this ticket!
