### ISSUE TITLE
externa file for users

### ISSUE THREAD

**Issue by r3nfolly** [Myster-Tee/TinfoilWebServer#10]
Hello Myster.

Is it possible to have the user's session on an external file? .csv or any other format?

Thanks

**Comment by matrixjaen18** [comment]
I have the same question, I would like to know how to add a list of users from a file and have the program update them without having to restart

**Comment by matrixjaen18** [comment]
I have not been able to modify the code to load users from outside but I have found another solution that is not bad either, I have created a script that reads the users from a text file and then creates the TinfoilWebServer.config.json file with the updated list of users, it also shows you the total number of allowed users and scans the list every 10 minutes to update. I can pass the code if the creator agrees

**Comment by r3nfolly** [comment]
Myster, pleaseeeee, allow matrixjaen to update this for us. pleaseeeeeeeeeeeeeeeeeee

**Comment by CodeHedge** [comment]
I made a python script that modifies the config.JSON. It's adds users to the config and the application already adds them without a restart. Even shows up in the logs as it runs. 

I have problems with slow transfer speeds. I top out at like 3MB/s

**Comment by r3nfolly** [comment]
Hey Myster, please, don't forget about us.

Thanks

**Comment by Myster-Tee** [comment]
What is exactly the point here ? You want a separate file for declaring allowed users, instead of everything in the TinfoilWebServer.config.json ?

**Comment by r3nfolly** [comment]
Yes, have an external file for more users, to be easier to modify, like a .csv or xls maybe, I don't know if is possible.
If the WebServer config can read the file every few minutes.

**Comment by Myster-Tee** [comment]
I propose the [following solution](https://github.com/Myster-Tee/TinfoilWebServer/issues/18#issuecomment-1762928141), would it be ok for you?

**Comment by Myster-Tee** [comment]
1.6.0 should do the trick for you.
