### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by JMaroz** [Myster-Tee/TinfoilWebServer#11]
Hello,

i successfully start the TinfoilWebServer after some trouble. 

The main issue was to find the correct ip to insert into the tinfoil configurations when i run the software.  ̶I̶s̶ ̶p̶o̶s̶s̶i̶b̶i̶l̶e̶ ̶t̶o̶ ̶"̶p̶r̶i̶n̶t̶"̶ ̶t̶h̶e̶ ̶m̶a̶c̶h̶i̶n̶e̶ ̶i̶p̶ ̶w̶h̶e̶n̶ ̶T̶i̶n̶f̶o̶i̶l̶W̶e̶b̶S̶e̶r̶v̶e̶r̶ ̶i̶t̶ ̶s̶t̶a̶r̶t̶e̶d̶ ̶l̶i̶k̶e̶ ̶i̶t̶ ̶h̶a̶p̶p̶e̶n̶s̶ ̶f̶o̶r̶ ̶t̶h̶e̶ ̶j̶s̶o̶n̶ ̶c̶o̶n̶f̶i̶g̶u̶r̶a̶t̶i̶o̶n̶?̶ (
i just find that the ip was printed in the terminal
[I] Current machine Host/IP:
        MacBook-Pro-di-Andrea.local
        127.0.0.1
        192.168.73.104

 I suggest to add "how to find the ip" for tinfoil in the readme. 

Thanks.

P.s. after that TinfoilWebServer works like a charm 😄

**Comment by Myster-Tee** [comment]
Done
