### ISSUE TITLE
Crashes upon starting

### ISSUE THREAD

**Issue by Sevyn13** [Myster-Tee/TinfoilWebServer#13]
I have downloaded the dependent version as well as the ASP.net runtime. When I click the .exe the window pops up for a brief second then disappears. I have tried on two different computers and tried with an untouched config as well.

**Comment by r3nfolly** [comment]
If you change the config in a way the app doesn't like, does that. I learned the hard way. Testing.

**Comment by Sevyn13** [comment]
Thank you, but it is not the config. I can get the independent version to work but I cannot get the dependent version to work.

**Comment by Myster-Tee** [comment]
Which OS are you running the app?
