### ISSUE TITLE
Google drive integration 

### ISSUE THREAD

**Issue by AlienRetroGaming** [Myster-Tee/TinfoilWebServer#14]
I was wondering if you can store a load on content on a google drive and use that with your app as i'm running out of space and my upload is taking a beating.

**Comment by Myster-Tee** [comment]
I don't have much time to develop actually, but just to make sure I understand your need, in addition to setting up a list of locally served directories you would like to be able to setup a google drive link which would be be scanned by the application for serving available google drive files ?

**Comment by Myster-Tee** [comment]
See *CustomIndexPath* property from version 2.0.0.
