### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by r3nfolly** [Myster-Tee/TinfoilWebServer#16]
Hello Myster.
I have used the TinfoilWebServer a quite some time now, thanks for the great job.
My setup is CloudFlare - Unraid - VM - TinfoilWebServer.

So I enabled Proxy on the config, what happens is, that I always get the message about disabling proxy, and when I have someone trying to access multiple times, the IP that blocks is from the NGINX, not from the real IP source.  There is any way to sort this?

Thanks again.

**Comment by Myster-Tee** [comment]
It looks like it is an NGINX problem which doesn't emit the X-Forwarded-For header with the original IP address.
Check your NGINX reverse proxy config, and make sure this feature is supported.
This problem is not a TinfoilWebServer issue, I close it.
