### ISSUE TITLE
Docker, move config directory

### ISSUE THREAD

**Issue by Corgano** [Myster-Tee/TinfoilWebServer#18]
I found the instructions to load tinfoilwebserver in docker, and it works, but the config files are in the app root directory and are hard to access. Any way to move them to somewhere more accessible EX parent folder of the games folder?

**Comment by Myster-Tee** [comment]
I suggest adding a command line option for specifying the config file; example:
```
TinfoilWebServer.exe --config "some config file path.json"
```
Would it be ok for you?

**Comment by Corgano** [comment]
I'm not sure how that would work in docker

What I know works and seems to be the norm, is having a separate config
folder, and then mapping it as a volume to somewhere writable. For instance
mapping /host -> /mnt/switch/!Main works great. If I could also map /config
-> /mnt/switch/shop config then I'd be set. Then all the configs could be
placed /loaded from the /config folder

**Comment by Corgano** [comment]
Any updates on this?

**Comment by Myster-Tee** [comment]
I just released v1.6.0 try it and let me know if it is fine for you.

**Comment by Corgano** [comment]
Does this let you specify a file name, or just the directory? Ex if I run 3
instances would I need to have a configs folder with 3 separate directories
one for each instance, or can I have the configs folder with 3 different
filenames one for each instance?

**Comment by Sevyn13** [comment]
> I found the instructions to load tinfoilwebserver in docker, and it works, but the config files are in the app root directory and are hard to access. Any way to move them to somewhere more accessible EX parent folder of the games folder?

Could you share where you found the guide to run it in Docker?
