### ISSUE TITLE
Can you make a more indepth tutorial? I am struggling to set it up

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [Myster-Tee/TinfoilWebServer#19]
title says it all. Would be much apreciated as idk how to do stuff like get a server pointing towards my ip address lol

**Comment by Myster-Tee** [comment]
A server does not point to an IP address but listens to it, maybe you're talking about DNS ?
I would recommend you reading literature on networking principles (LAN ou WAN ), how to run local servers, etc...

Anyway, your question is not a TinfoilWebServer issue, I close it.
