### ISSUE TITLE
json config issue

### ISSUE THREAD

**Issue by epiclulz666** [Myster-Tee/TinfoilWebServer#2]
json file becomes un parseable when you make any edits to it
the app runs ok when you leave the config file alone and dont edit anything

```
C:\Users\User\Desktop\TinfoilWebServer_Framework-Dependent_v1.2.0>TinfoilWebServer.exe
Failed to build configuration: Could not parse the JSON file.
Is «TinfoilWebServer.config.json» a valid JSON file?
```

**Comment by epiclulz666** [comment]
worked it out. the directory cant be more then 1 deep for it to scan. on an unrelated note is there anyway to password protect the shop ?

**Comment by Myster-Tee** [comment]
There is NO depth limitations for the directories. In the JSON, just don't forget to escape the backslashes with another one.
In the moment, there is no option to protect the shop with a password, but I'll think of it.
