### ISSUE TITLE
Issue using extra repositories feature

### ISSUE THREAD

**Issue by CodeHedge** [Myster-Tee/TinfoilWebServer#20]
"ExtraRepositories": string[],        // A set of extra repositories sent to Tinfoil for scanning (see https://blawar.github.io/tinfoil/custom_index/ for more information)

So, I read the documentation on https://blawar.github.io/tinfoil/custom_index/ and i'm still not entirely sure what to place in this field. Ultimately i would like to utilize the gdrive options in the custom_index documentation

in "ExtraRepositories", do i place the path to a CustomIndex.tfl? Is it just a path to another directory contains files? I don't see where in the blawar.github it says how to specify anything without creating a custom tfl file.

**Comment by Myster-Tee** [comment]
Actually "ExtraRepositories" is mapped to the "directories" property documented in "Basic Format" section  of official doc [here](https://blawar.github.io/tinfoil/custom_index/).

**Comment by CodeHedge** [comment]
Ahhh I see. So, that would also mean that gdrive isn't supported huh?

**Comment by Myster-Tee** [comment]
I don't really understand what you to do, the goal of TinfoilWebServer is to serve local server files over the network (LAN or WAN), but gdrive is not local to the server.
So what do you want? Do you want to mix local files and gdrive files ? You want to serve only gdrive files? Other ?

**Comment by CodeHedge** [comment]
Exactly, I want to use both local files and Gdrive files. Looking at the tinfoil network setup info there is a way to link Gdrive files in the shop.tfl. My upload from my home when I'm working remotely is pretty slow. But I have a large Gdrive storage and their upload is ideal when I'm a WAN client.

![image](https://github.com/Myster-Tee/TinfoilWebServer/assets/35341367/9855c9d0-784b-427d-a3b0-ac12cd690242)![image](https://github.com/Myster-Tee/TinfoilWebServer/assets/35341367/0271cc70-629e-443e-91a4-d493f2058352)

**Comment by CodeHedge** [comment]
I was able to get the Gdrive files working on a custom tfl file I made. I can share the structure of a valid entry if needed. I wouldn't know how to implement it into your code though.

**Comment by Myster-Tee** [comment]
Good news. I'm actually drafting a new version which would allow to specfiy any JSON properties from BLAWAR's documentation.
It would be nice if you can share your structure so that I ensure my new design will fit your need.

**Comment by Myster-Tee** [comment]
The new v2.0.0 integrates a new setting called *CustomIndexPath* which should help you to do what you want.
