### ISSUE TITLE
Hello i am trying to set Blacklist for username

### ISSUE THREAD

**Issue by TeymurDevv** [Myster-Tee/TinfoilWebServer#22]
Hello can you help me to set a blacklist feature for Usernames
When multiple ips trying to login to a same account i want to blacklist
And when login credentials is false i want to blacklist the username i can't do it I have never do some stuff in C#
I am a PHP developer =) Can you help me please...

**Comment by r3nfolly** [comment]
This is really a nice idea.

**Comment by TeymurDevv** [comment]
I think soo...
We are waiting a reply from @Myster-Tee <3

**Comment by Myster-Tee** [comment]
From my point of view, blacklisting a user is not a good strategy as it might block legit users.
In version 2.0.0, I introduced a fingerprint filter to restrict access to some devices automatically!
