### ISSUE TITLE
User device restriction?

### ISSUE THREAD

**Issue by DamienSilvert** [Myster-Tee/TinfoilWebServer#23]
Hello, first of all congratulations and thank you for your work. Would it be possible that, in addition to username and password, the unique ID or MAC of the switch would be used so that each user could access only from one or two devices?

Something like this?

{
        "Name": User1,                 // The user name
        "Pwd": PwdUser1,                  // The password
        "MAC": XX:XX:XX:XX:XX:XX,   //MAC adress of the switch 
        "MessageOfTheDay": string       // Custom message for the user
      }

**Comment by Myster-Tee** [comment]
Version 2.0.0 integrates a fingerprint filter.
