### ISSUE TITLE
I think the macOS build in the Releases page isn't working

### ISSUE THREAD

**Issue by rogerluan** [Myster-Tee/TinfoilWebServer#25]
Hello 👋 

I tried downloading an independent version for macOS and the folder structure doesn't seem right. Here are some of the latest versions I tried downloading:

<img width="1276" alt="image" src="https://github.com/Myster-Tee/TinfoilWebServer/assets/8419048/bfc8e822-2236-46ab-8614-a81839fbc0de">

See how the path look malformatted? Maybe it was an issue when distributing the builds.

Any help here? I'd like to try this out 😊 

Thanks in advance!

**Comment by Myster-Tee** [comment]
You mean that you are missing the "TinfoilWebServer_v1.6.0_Framework-Independent-osx-x64" folder, right?
Which decompression program are you using? Can you try another one?

**Comment by rogerluan** [comment]
I'm not using any particular decompression program, macOS automatically extracts zip files on our behalf, it's transparent to the user 👀

**Comment by rogerluan** [comment]
Good call about the decompression program though, I managed to download the raw .zip disabling Safari's automatic package extraction, and then I extracted it using macOS's built-in decompression tool and it worked! 🎉 

I'm facing another issue now, though: it can't find my folder 👀 

```js
{
  "ServedDirectories": [ "/Users/rogerluan/Documents/Nintendo\\ Switch/games/switch" ],
  "StripDirectoryNames": true,
  "ServeEmptyDirectories": false,
…
…
```

(also tried with single `\` without spaces, didn't work either)

Getting this error:

<img width="691" alt="image" src="https://github.com/Myster-Tee/TinfoilWebServer/assets/8419048/78248a67-c230-497b-ae78-4d7389e697cc">

The real path is `/Users/rogerluan/Documents/Nintendo Switch/games/switch` (no backslash, just a space that needs to be escaped probably)

**Comment by rogerluan** [comment]
Is there anything you can do on your end to fix the decompression issue? Maybe a simpler file structure? No special characters in the path maybe? No clue 🤷‍♂️  
I haven't faced this problem with any other zip files I've downloaded

**Comment by Myster-Tee** [comment]
> Good call about the decompression program though, I managed to download the raw .zip disabling Safari's automatic package extraction, and then I extracted it using macOS's built-in decompression tool and it worked! 🎉
> 
> I'm facing another issue now, though: it can't find my folder 👀
> 
> ```js
> {
>   "ServedDirectories": [ "/Users/rogerluan/Documents/Nintendo\\ Switch/games/switch" ],
>   "StripDirectoryNames": true,
>   "ServeEmptyDirectories": false,
> …
> …
> ```
> 
> (also tried with single `\` without spaces, didn't work either)
> 
> Getting this error:
> 
> <img alt="image" width="691" src="https://user-images.githubusercontent.com/8419048/284414508-78248a67-c230-497b-ae78-4d7389e697cc.png">
> The real path is `/Users/rogerluan/Documents/Nintendo Switch/games/switch` (no backslash, just a space that needs to be escaped probably)
> 
> EDIT: Nevermind, I removed the space escaping and it worked! 🎉 `"ServedDirectories": [ "/Users/rogerluan/Documents/Nintendo Switch/games/switch" ],`

Only double quotes ["] and backslashes [\] need to be escaped with a preceding backslash [\]. Not spaces (this comes from JSON specification).

**Comment by Myster-Tee** [comment]
> Is there anything you can do on your end to fix the decompression issue? Maybe a simpler file structure? No special characters in the path maybe? No clue 🤷‍♂️ I haven't faced this problem with any other zip files I've downloaded

I could probably do something for this, it's all about UNIX and Windows directory separator char [/] or [\], but I've no time for this.
