### ISSUE TITLE
Low download speed

### ISSUE THREAD

**Issue by DamienSilvert** [Myster-Tee/TinfoilWebServer#28]
Hi, i have the server running on windows and the download speed never surpass the 10Mb/s, my internet connection  works fine and my Ethernet card its gigabyte 2.5Gb. Does the server restrict the speed per download, or do you think its a windows thing?
Do any of you have some pointers on how to improve the download speeds? i normally don't work with windows and its driving me crazy.

**Comment by Myster-Tee** [comment]
This speed is only due to hardware limitation of the Nintendo Switch itself.
Around 10MB/s is the best you can have.
