### ISSUE TITLE
Possibility of added password protection?

### ISSUE THREAD

**Issue by wstmreddit** [Myster-Tee/TinfoilWebServer#3]
I really like this app, very easy to use and I found you on GBATemp which is always great for finding stuff like this. I use this as I travel a lot for work and leave my computer on and RDP into it from my phone from afar and add stuff I want as I go place. Issue is, I am getting constant port scans and I am worried they theyre eventually going to find a way into the main system with this running. For that reason I am wondering if I can add password protection, or if its only possible through configuring the windows http server

I really appreciate you and any help

**Comment by wstmreddit** [comment]
I only have one port in and one port out opened, nothing DMZ'd or anything stupid. But I just do not feel like the windows http server is that secure

**Comment by Myster-Tee** [comment]
Implemented in v1.3.0.
