### ISSUE TITLE
PlainText Works - Sha256 Password Incorrect

### ISSUE THREAD

**Issue by r3nfolly** [Myster-Tee/TinfoilWebServer#35]
Hello again.

If I set up the authentication as Sha256, I get " password incorrect" . And I'm using something simple to test. On plaintext works fine. 

        "Name": "renato",
        "Pwd": "123",
        "MaxFingerprints": 3,
        "CustomIndexPath": null

Am I doing something wrong?

**Comment by jecoteco** [comment]
Password must be in SHA256 encrypted format not "123"

**Comment by r3nfolly** [comment]
Thank you so much, now works.

**Comment by Myster-Tee** [comment]
> Password must be in SHA256 encrypted format not "123". In this case the encrypted password would be "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3". Type "123" as password in tinfoil with this and it will accept. There are a number of web sites and programs that can convert for you. Keep in mind that a SHA256 password can not be decrypted so don't forget your password.

Thanks for doing support @jecoteco ;)
