### ISSUE TITLE
Running on linux

### ISSUE THREAD

**Issue by DevilStyle** [Myster-Tee/TinfoilWebServer#7]
Hello, congratulations for your project, I wanted to ask you how it is possible to start the server on linux, I downloaded the linux package but I can't start it. Thank you

**Comment by Myster-Tee** [comment]
You need to install .NET Runtime 6 for Linux from [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0).
Pickup the version corresponding to your architecture (mostly x64).
