### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by r3nfolly** [Myster-Tee/TinfoilWebServer#8]
How I can set up the server to run on HTTPS-free generated certificate (like https://letsencrypt.org/)??
Thanks

**Comment by Myster-Tee** [comment]
I added an HTTPS example in the homepage documentation. This example is probably the easiest one, with best cross platform compatibility, but I invite you to browse official Microsoft documentation [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0) for more possibilities.

**Comment by r3nfolly** [comment]
Hello Myster-Tee, Thanks for the update. But I'm still suffering on HTTPs config. I can't understand the page :-(
Can you write how to run to https://localhost:5001, I have nginx on my unraid that will direct the traffic to the VM running the shop. but I have no idea how to write the script. Thanks for your help.
