### ISSUE TITLE
Multi User

### ISSUE THREAD

**Issue by thomin07** [Myster-Tee/TinfoilWebServer#9]
Hello, I installed TinfoilServer on Windows and I would like to know how to create several users for the connection please?

**Comment by Myster-Tee** [comment]
Simply edit "Users" section of the TinfoilWebServer.config.json like the example below for 3 users:

```json
"Users": [
  {
    "Name":  "SomeUserName1"
    "Pwd": "SomePwd1", 
    "MessageOfTheDay": "Hello user 1!"
  },
  {
    "Name":  "SomeUserName2"
    "Pwd": "SomePwd2"
  },
  {
    "Name":  "SomeUserName3"
    "Pwd": "SomePwd3", 
    "MessageOfTheDay": "Hello user 3!"
  }
]
```

"MessageOfTheDay" is not mandatory as you can see for "SomeUserName2".
